netlify/gocommerce

.gitignore
cmd/root_cmd.go
conf/configuration.go
conf/configuration_test.go
glide.lock
glide.yaml
mailer/mailer.go
main.go

This uses glide to do dependency resolution.
It also uses viper for configuration management

glide and configure the binary

---

.travis.yml
Dockerfile
Makefile
glide.lock
glide.yaml

There was also a missing dependency when I tried to build the project,
so I added it.

Add Dockerfile.

---

.gitignore
Dockerfile
api/api.go
api/helpers.go
api/index.go
api/order.go
api/payments.go
api/vatnumbers.go
cmd/migrate_cmd.go
cmd/root_cmd.go
cmd/serve_cmd.go
conf/configuration.go
glide.lock
glide.yaml
main.go

- Go 1.7.
- Logrus.
- Non-root user.
- Global variables.
- Extra configuration fixes.

Improvements to make it work on Heroku.

---

api/api.go
api/api_test.go
api/context.go
api/helpers.go
conf/configuration.go
conf/configuration_test.go
conf/reflect.go
conf/reflect_test.go

- introduces a trace method to wrap all the endpoints
- uses reflection to set the config
- simplifies the middleware stack

Part 1 of the admin ui

---

api/order.go
api/order_test.go
models/address.go

this doesn't test the actual creation which still needs a long test but was having troubles

add create tests

---

Makefile
conf/configuration_test.go

Fix Makefile to not exclude all directories.

---

api/api.go

Add log to the api.

---

api/api.go
api/api_test.go
api/context.go
api/order_test.go
api/payments.go
api/payments_test.go
api/paypal.go
api/user_test.go
cmd/serve_cmd.go
conf/configuration.go
config.example.json
glide.lock
glide.yaml

Make sure we can handle payment flows based on paypal as well

Paypal integration

---

api/api.go
api/order.go
api/order_test.go
api/pagination.go
api/params.go
api/payments.go
api/reports.go
api/user.go
api/user_test.go
api/utils_test.go
conf/configuration.go
models/connection.go
models/event.go
models/order.go
models/user.go

This introduces the concept or "roles" in the "app_metadata' of the JWT
instead of a "group" to be in line with Auth0.
Also ads more options for sorting apart from just created at
Adds an "order_count" attribute to the user object and sets up orders for
a specific user as a proper resource under /uesrs/:user_id/orders
Makes is possible to update order status and addresses regardless of the order
state.

Changes needed for the new admin ui

---

api/index.go
cmd/serve_cmd.go
conf/configuration_test.go

these were pointed out by @verythorough

fix some missed old names

---

app.json
www/site/data/landing.yaml
www/site/static/_redirects

- Add app.json with env variables.
- Remove redirect.

Fix Heroku button integration.

---

app.json

Fix json format.

---

.travis.yml

These notifications are killing my inbox.
This project should work with the most recent release of go.

Turn email notifications off and update Go.

---

README.md
api/params.go
config.example.json

**- Summary**
This updates the example config file and the README.  The example json had a few errors in it that didn't match what config parser was looking for, and the README didn't mention the recent PayPal requirement.
- Update example.config.json
- Note the PayPal configuration requirements

Update docs and example

---

Makefile

This should make it so that we can release binaries to GH easily

update to have release parts

---

config.example.json

Fixes #1
**- Summary**
The JSON structure was mismatched with the actual configuration.
No tests needed.
Fix example mailer config to match structure.

Fix mailer example config

---

api/coupons.go
api/coupons_test.go
api/download.go
api/index.go
api/order.go
api/order_test.go
api/payments.go
api/payments_test.go
api/reports.go
api/user.go
api/user_test.go
api/vatnumbers.go
assetstores/netlify.go
coupons/coupons.go

**- Summary**
Use of HTTP status code constants instead of magic numbers.
Existing automated tests.
Use of HTTP status code constants instead of magic numbers.

Use constants for HTTP status codes

---

api/payments.go
api/payments_test.go

**- Summary**
Preauthorizing a PayPal payment was the only API route to use form encoding. I added JSON support to be consistent, but left the form encoding support. The PayPal checkout.js library will use form-encoding by default, and supporting both for now will not break backwards compatibility.
Added tests for both form encoding and JSON.
Add JSON encoding support to PayPal preauthorize route.

Add support for JSON to create a PayPal preauthorization

---

api/order.go
mailer/mailer.go
mailer/noop.go

Fix MailTemplate for Receipt Endpoint

---

api/instance.go
api/user.go
models/helpers.go
models/instance.go
models/line_item.go
models/order.go
models/user.go

Cascade delete instance data

---

api/api.go
api/api_test.go
api/router.go

Do not log health check endpoint

---

api/instance.go
api/instance_test.go

Do not merge instance config on update

---

README.md
conf/configuration.go

Add configuration docs

---

api/api.go
api/coupons.go
api/order.go
api/settings.go
conf/configuration.go
coupons/coupons.go

These endpoints will be useful for the admin UI.

Add /coupons and /settings endpoints for admins

---

api/order.go
api/payments.go
models/hook.go

When using gocommerce in multi tennant mode, we should be able to have webhooks be relative to the SiteURL for the request.

Make relative webhooks work in multi tennant mode

---

api/download.go
api/middleware.go
context/context.go
coupons/coupons.go

Allow setting a relative URL for the coupon settings, and resolve that relative to the SiteURL.

Allow relative URLs for coupon settings

---

coupons/coupons.go
coupons/coupons_test.go

Adds some tests, and fixes the expriation logic, but no functional changes

minor fixes to the coupon expiration

---

api/payments.go

The confirmation emails weren't listing downloads. Now they are.

preload the downloads for templates

---

api/order.go
api/utils_test.go
calculator/calculator.go
calculator/calculator_test.go
calculator/test/settings_fixture.json
claims/claims_test.go
claims/test/jwt_payload_fixture.json
models/order.go

So we know the user claims and discounts applied to each item.

Add traces to calculate order prices.

---

api/api.go
api/api_test.go
api/db_logger.go
api/download.go
api/instance.go
api/instance_test.go
api/log.go
api/middleware_test.go
api/order.go
api/payments.go
api/payments_test.go
api/reports.go
api/user.go
api/utils_test.go
cmd/migrate_cmd.go
cmd/multi_cmd.go
cmd/root_cmd.go
cmd/serve_cmd.go
conf/configuration.go
context/context.go
models/connection.go
models/connection_logger.go

**- Summary**
I got really annoyed at how the logging setup and sql logging worked so I changed that.
Refactor only. Tests are passing.
Refactor log handling

Logging cleanup

---

api/order_test.go
models/line_item.go

*Fixes #191*
**- Summary**
There was a bug where downloads from the last line item would overwrite other downloads in an order. This is fixed.
Added regression test.
Fix bug with missing downloads on orders with multiple items

Fix downloads being overwritten when having multiple items

---

Makefile

Do not run tests every time the binary is built

[make] Remove test dependency

---

payments/paypal/paypal.go

**- Summary**
Transaction updates on paypal can fail for weird reasons.
Let not stop those from making a successful payment.
Hotfix, tests passing
Ingore error when updating paypal transaction details

Ignore error when updating paypal transaction details

---

api/payments.go

We also need to send emails on the payment create endpoint.

Also send confirmation on payment create

---

go.mod
go.sum

**- Summary**
The mysql driver needs to be upgraded for Go 1.17
Testing on staging
Upgrade dependencies

Upgrade some dependencies to make mysql connect work
