README.md, api/api.go, api/helpers.go, api/order.go, api/payments.go, config.example.json, models/line_item.go, models/order.go, models/site_settings.go
This includes some API changes. Mainly the line items only
require a Path and a Quantity and are verified when added.
Gocommerce will now check the site for a /gocommerce/settings.json
file that can currently set VAT rules based on countries/product types.
An amount must be included when triggering a payment, to verify that
the tax calculations the user has been shown in the UI matches what we
are actually going to charge.
=> Add support for VAT calculations and site settings

Dockerfile, LICENSE, README.md, api/api.go, api/helpers.go, api/index.go, api/order.go, api/payments.go, cmd/root_cmd.go, conf/configuration.go, glide.lock, glide.yaml, mailer/mailer.go, main.go, models/connection.go
Making the project more consistent with our branding.
- Add LICENSE file and links.
- Handle some backwards compatible settings to make migration easier.
=> Rename project to Netlify Commerce.

Dockerfile, README.md, api/api.go, api/helpers.go, api/order.go, api/payments.go, cmd/root_cmd.go, glide.lock, glide.yaml, mailer/mailer.go, main.go, models/connection.go
=> Add name prefix everywhere.

cmd/migrate_cmd.go, cmd/root_cmd.go, conf/configuration.go, models/address.go, models/connection.go, models/line_item.go, models/order.go, models/order_notes.go, models/site_settings.go, models/transaction.go, models/user.go
This is useful if you want to have two services in the same database
and don't want table names to collide.
- Auto migrate tables on demand.
=> Allow to namespace the database tables.

api/order.go, api/order_test.go, api/payments.go, api/paypal.go, api/utils_test.go, models/line_item.go, models/order.go
In some cases a line item consists of different products bundled together. Legally we need to calculate the VAT based on the different types of product and their individual parts of the price.
This PR changes the time of the pricing calculation to when the order is created, and handles VAT for bundles.
=> Handle tax calculations for pricing bundles

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, Makefile
This change adds some missing files in this repository:
- Templates for GitHub issues and pull requests.
- Code of conduct.
- Contributing guide.
=> Add missing project management files.

www/site/static/_redirects
**- Summary**
The docs site isn't ready, but we want to use its domain in articles now.
I tested in the Netlify Playground
Temporary redirect to GitHub repo
=> Add temporary redirect to repo

api/order.go, api/order_test.go, api/params.go, api/user_test.go, glide.yaml
**- Summary**
This PR adds a tweak to the email filter for the UserList endpoint and adds an email and items filter to the OrderList endpoint.  The purpose of the changes is to enable some basic search functionality in the [gocommerce-admin](https://github.com/netlify/gocommerce-admin/pull/2).
I wrote some tests similar to the ones that existed that test these code paths.
- Changed Email filter on the UserList endpoint is now a partial match filter.
- Added Email and Items filter to OrderList endpoint.  Both will return partial matches.  The Items filter matches against the LineItems title field.
=> Add route filters for users and orders search

api/context.go, api/order.go, api/user.go, api/utils_test.go, calculator/calculator.go, calculator/calculator_test.go, claims/claims.go, conf/configuration.go, models/coupon.go, models/line_item.go, models/order.go
This adds support to defining member discounts in the gocommerce settings files.
Coupons (and member discounts) also gets a fixed discount option that sets the discount to a specific amount
=> Support member discounts and fixed coupon amounts

Dockerfile
**- Summary**
Binary is not executable inside the Docker image
The binary is built for Darwin, not Linux
```
$ make image
[...]
Successfully built a7e7971f5351
$ docker run -ti a7e7971f5351
standard_init_linux.go:187: exec user process caused "exec format error"
```
Fix the binary build inside the Docker image
=> [Dockerfile] Fix build command

.gitignore, api/api.go, mailer/mailer.go, mailer/mailer_test.go, mailer/noop.go
Fixes #53
**- Summary**
This makes the mailer configuration optional instead of required. Emails can be handled by the payment provider, such as Stripe.
Automated tests added.
If an invalid mailer config is provided, use a noop mailer instead of failing.
=> Add noop mailer to use if no mailer config present

api/payments.go, api/payments_test.go, payments/payments.go, payments/paypal/paypal.go, payments/stripe/stripe.go
Fixes #58
**- Summary**
Add support for PayPal refunds.
Modified existing automated test to verify refunds work correctly.
Add support for PayPal refunds.
=> Add support for PayPal refunds

api/api.go, api/api_test.go, api/payments.go, api/payments_test.go, api/utils_test.go, conf/configuration.go, config.example.json, context/context.go
**- Summary**
Payment providers must be enabled in the configuration explicitly.
Creating a payment must explicitly specify which payment provider to use via the `provider` parameter.
Automated tests pass.
Re-add support for multiple payment providers, but require explicit selection and enabling.
=> Re-add support for multiple payment providers

.gitignore, api/order_test.go, api/user_test.go, api/utils_test.go, models/address.go
**- Summary**
Singular names are easier to deal with and accomodate all the different styles of naming without assuming a Western-style first and last name. Also, most payment processors only expect a singular name.
Existing automated tests pass
Use a single `name` for addresses, instead of `first_name` and `last_name`.
=> Combine address first_name and last_name

api/api.go, glide.lock, glide.yaml
**- Summary**
This allows the server to finish in-progress requests before stopping.
Local testing with Ctrl-C.
Add graceful shutdown of server in response to SIGINT and SIGTERM.
=> Add graceful shutdown of HTTP server

api/api.go, api/payments.go
**- Summary**
This route is not needed in the PayPal payment flow. It was previously being used to obtain the `payerID`, but `payerID` is being passed by PayPal's checkout.js to the client-side handler, so a call to gocommerce to obtain the `payerID` is not needed.
All tests pass.
Remove unneeded get PayPal payment route.
=> Remove unnecessary paypal route

api/api.go, api/middleware.go, api/payments_test.go
**- Summary**
Go does not populate `http.Request.GetBody` for server requests.
Added test that confirmed previous panic and now passes.
Populate `http.Request.GetBody` for routes that need to read the body multiple times.
=> Add middleware that populates GetBody

api/payments_test.go, payments/stripe/stripe.go
**- Summary**
Creating stripe payments was failing because it was not deserializing the `stripe_token` parameter correctly.
Added a basic test that verifies all our logic works correctly, while mocking the actual Stripe interactions.
Deserialize `stripe_token` correctly when creating Stripe payment.
=> Fix creating a stripe payment

README.md, api/download.go, api/order.go, api/payments.go, api/payments_test.go, models/transaction.go
**- Summary**
The transaction was previously being set to the `pending` status, but nothing would ever update it to `paid`. This would prevent the ability to issue refunds. In contrast, the order **was** being marked as `paid`. 
Added assertions to existing payment creation tests.
Set transaction to "paid" upon successful charge.
=> Set transaction to paid on successful payment

api/api.go, api/order.go, mailer/mailer.go, mailer/noop.go
This adds a `/orders/:order_id/receipt` endpoint that will return the HTML receipt for the order.
By default this uses the same HTML templates as the OrderConfirmation Mailer, but the endpoint takes an optional `template` query parameter that specifies another template inside the website that can be used to generate different variation of the receipt (one for the client, maybe one for printing on a box, one representing a ticket, etc)....
=> Receipts endpoint

api/order.go, api/order_test.go, api/params.go, api/utils_test.go
Fixes #76 
**- Summary**
Add order filters:
`billing_name`
`shipping_name`
`item_type`
`coupon_code`
Added tests for new filters.
Add additional order filters.
=> Add additional order filters

api/api_test.go, api/middleware.go, api/payments_test.go, api/utils_test.go, cmd/serve_cmd.go, conf/configuration.go, mailer/mailer.go, mailer/mailer_test.go
This implements the same distinction between smtp and mail settings
that gotrue uses.
=> Make mailer use global configu if no smtp settings in instance

models/hook.go, models/instance.go, models/line_item.go, models/order.go, models/order_notes.go, models/transaction.go
Default gorm string column size is 255, which is not sufficient for some columns.
=> Add column type to force MySQL

models/line_item.go
Downloads were getting persisted without any order ID, which means they never show up when querying for the order.
=> Fix downloads getting persisted without order id

api/payments_test.go, payments/paypal/paypal.go
This caused paypal b ased checkouts to error out based on a wrong transaction value, since we always work with amounts in cents as an integer, but paypal's API expects a string in decimal format.
=> Paypal expects amount to be xx.xx not xxxx

mailer/mailer.go
This makes it possible to us `{{ .SiteURL }}` in the templates to generate links back to the site.
=> Add SiteURL as a template var for the mailer

calculator/calculator.go, calculator/calculator_test.go
Golang doesn't have a math.Round method yet, and so far we had been using this implementation:
https://gist.github.com/siddontang/1806573b9a8574989ccb
However, it turns out that implementation fails on 150.5 and rounds to 150 instead of 151.
This PR adds the rounding method from https://github.com/golang/go/blob/master/src/math/floor.go#L58 which seems to on the way to become a part of the std lib.
=> Fix rounding function

README.md, app.json
Add the button to the readme and updates app.json so it works.
Includes:
- Automatic deployment of Heroku's Postgres DB service
- Automatic generation of the JWT secret
- Automigrate set to true
- Optional fields to add Stripe integration
- Optional fields to add mail sending
- Help text for all fields
=> Add working Deploy to Heroku button

api/payments_test.go, glide.lock, glide.yaml, payments/paypal/paypal.go
**- Summary**
The PayPal API only returns 20 random web experience profiles. The pagination parameters do not function, and there is no way to retrieve a profile by name, but names must unique.
This change creates a temporary profile for each payment.
Automated tests pass.
Use temporary web experience profiles per PayPal payment.
=> Create temp paypal web experience profiles

Makefile
Apparently due to https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58 `go get` now rejects installing via the github mirror.
=> Fix path to install golint from

Makefile, api/middleware.go, api/middleware_test.go, api/utils_test.go
**- Summary**
When there are no payment providers enabled, the process starts up fine, but will panic on a call to any instance specific endpoint.
My commit fixes this by not wrongly returning nil for the error.
Included are the following test:
- Initial e2e test for `WithInstanceConfig` in context of calling `/settings`
- Regression test for `WithInstanceConfig` modeling the case when no payment providers are enabled
Fixed a bug in multi-instance mode when no payment methods are configured.
=> Fix runtime panic when no payment providers are enabled

api/order_test.go, api/pagination.go, api/user_test.go, api/utils_test.go, glide.lock, glide.yaml
Fixes #122
**- Summary**
There was an issue with counting total records in queries with joins / groups. An update of Gorm fixed this.
Since the tests are actually not mocking gorm, I am confident that the upgrade will not break anything.
I added tests for verifying the pagination headers for *user* and *order* endpoints.
Fix pagination on user listing endpoint
=> Fix pagination for user listing

api/user.go, api/user_test.go, models/user.go
Fixes #121 
**- Summary**
For every user object in the user listing this will add a timestamp of the creation of the most recent order for that user.
The issue actually mentions a field with the id of the most recent order. This is actually really complex in terms of the current query that is used and doing `MAX(orders.created_at)` seemed more straight-forward since the frontend design for `gocommerce-admin`  shows a timestamp.
@RoseannaM can you tell me if this is sufficient?
If we need to be able to link to the most recent order in the frontend, I can come back to this and figure out a good way to provide the ID, too.
An assertion for the `LastOrderAt` field has been added in the user listing test.
Provide a timestamp of the most …
=> Show timestamp of most recent order for users

.travis.yml
**- Summary**
Travis was using Go 1.8 for testing and it seems like golint is not working for Go 1.8 anymore, at least temporarily.
I decided the upgrade would be a good thing to do. We should also consider upgrading higher soon.
Fix CI build by using go 1.9
=> Upgrade go in TravisCI to version 1.9 to fix the install of golint

api/order.go, api/order_test.go, api/user.go, api/user_test.go, api/utils_test.go, models/user.go
Fixes #120
**- Summary**
When a order is made while a user is logged in (JWT passed along) and it is their first order, a new user object will be created in gocommerce.
This PR introduces a new field for the user object: `name`
It will be set only on creation of the user.
In order to determine the user's name, the following fields are considered in this order:
- `UserMetadata["full_name"]` from JWT claims *(this is what the Identity Widget uses)*
- `BillingAddress.Name` from order
- `ShippingAddress.Name` from order
I created a test suite covering the creation of a user on their first order.
It also verifies the name field in the different cases.
Persist user's name from JWT or order on their first order
=> Persist username from JWT or order

api/reports.go, api/reports_test.go
Fixes #135
**- Summary**
The sales reports endpoint should contain the number of orders to be able to calculate averages.
Added a test for the sales report endpoint
Report number of orders for each currency on sales report
=> Report number of orders for each currency on sales report

api/api.go, api/params.go, api/user.go, api/user_test.go
Fixes #136 
**- Summary**
In order to delete multiple users issue a `DELETE` call to `/users`.
Multiple `id` query parameters will determine which users should be deleted.
Example:
```
DELETE /users?id=user1&id=user2&id=user3
```
This is the closest you get to implementing bulk deletion in REST.
It should also be compatible to how [qs (js lib)](https://www.npmjs.com/package/qs) handles a parameter with multiple values. (Use `{ indices: false }` in the options.)
*This action is meant to be idempotent:*
If you pass ids which don't exist it will not result in an error. This enables sending the same request multiple times if the first request failed and only some users got deleted. Although internally it uses a transaction to rollback changes if one delete fails, idempotency is still a best …
=> Allow deletion of multiple users

api/order_test.go, api/payments_test.go, api/user_test.go
**- Summary**
This removes some bloat from the tests:
There were many places where database changes the test made would be rolled back manually. This is an antipattern that relies too much on implementation details of the tested code.
The better way to do this is creating an empty database before each test run. This is actually already happening:
Since `NewRouteTest` will always create a new sqlite database and
it is run at the start of every test that is run, we are sure to
not have any effects of tests interfering eachother via the database.
Refactor test code
=> Refactor tests globally to not rollback db changes manually

api/order_test.go, api/params.go, models/order.go
Fixes #119
Regards #137
**- Summary**
With this change, orders can be filtered by `payment_state` and `fulfillment_state`.
These values are allowed:
- for `payment_state`
- `pending`
- `paid`
- `failed`
- for `fulfillment_state`
- `pending`
- `shipped`
- `failed`
There are now several filtering tests inside the `TestUserOrdersList` suite.
Implement filtering by payment and fulfillment state for order list
=> Implement filtering by state for order list

api/order_test.go, api/params.go
Fixes #137
**- Summary**
The admin UI has a requirement to show orders from "non-EU countries". This is only possible by filtering for orders not from countries inside the EU.
In order to get the opposite result to filtering by countries, an unequal sign (!=) can be used on `shipping_countries` and `billing_countries` fields.
Example: `/users/all/orders?shipping_countries=Germany,USA,Denmark`
The PR includes several test for use cases of filtering by country and one case for filtering negatively.
Allow negative filtering on address country of order
=> Allow negative filtering on order list for shipping / billing country

api/order.go, api/order_test.go, models/order.go
**- Summary**
In 7d46f178208b3173521f5d08e757cdb001941fc9 a list of possible values for `fulfillment_state` filtering was introduced.
This commit brings this list on-par with what is accepted when updating orders. Both operations now use the same list.
The order update test have been improved with checks for the `fulfillment_state` field.
Fix list of values for "fulfillment_state" when filtering orders
=> Fix possible values for fulfillment state

api/order_test.go, calculator/calculator.go, calculator/calculator_test.go, models/order.go
Fixes #129 
**- Summary**
The current behavior of GoCommerce is to apply discounts after calculating taxes.
This is valid for neither VAT nor sales tax based systems because taxes need to be applied to the final net amount. See #129 for more info and examples.
This PR includes several refactors to make the change easier.
The central commit (https://github.com/netlify/gocommerce/pull/155/commits/11df6e086ade577018d3f9dad77485c4e2899dbb) will change the calculation of a single item to this procedure:
- Get amount from item (net or gross)
- Subtract discount (fixed or relative) from this amount
- If prices include taxes, calculate the net amount (saved in field `net_total`)
- Calculate taxes from the net amount
- Calculate `total` by adding `net_total` + `taxes`
Introduces the field …
=> Fix calculation of taxes when items are discounted

api/errors.go, api/payments.go, api/payments_test.go, glide.lock, glide.yaml, payments/payments.go, payments/paypal/paypal.go, payments/stripe/stripe.go
Fixes #125
**- Summary**
This will add more info to the payments created with Stripe and PayPal.
For Stripe:
- Shipping Address
- Invoice Number
- Metadata (Order id)
For PayPal:
- Items with Quantity and Original Price
- Shipping Address
Paypal and Stripe payment tests have been extended with checks for the additional attributes.
Extend Stripe and PayPal payments with order metadata.
=> Add extra data to Stripe and PayPal payments

api/download.go, api/order_test.go, api/params.go, api/reports.go
Fixes #158
**- Summary**
There was a point where fields in  query filters were not prefixed with the correct table name in a join. This has been fixed.
Also contains another commit ensuring the table name is always taken from the ORM and is not a string literal.
A regression test for the fixed issue has been added.
Fix issue with sql error when querying orders with creation range
=> Fix error when querying by creation range

calculator/calculator.go, calculator/calculator_test.go
**- Summary**
There was a problem when using a quantity higher than 1 because
quantities were applied after rounding, therefore multiplying
rounding inaccuracies which is not acceptable.
Currently the amounts output in line items does not reflect the more
accurate values. There needs to be an API change to display single
and total amounts for items in orders.
Adjusted a test to take the now accurate amounts.
Fix increase of rounding inaccuracies through item quantity
=> Fix rounding inaccuracies with quantity

payments/stripe/stripe.go
**- Summary**
This fixes a recently discovered regression in the Stripe API where the `name` attribute is now required when supplying shipping info.
To test this, stripe would need to release a mock api server we could start with our tests. There is no other way to test for external api changes, since the Stripe SDK does not seem to catch this but rather only serializes the params to JSON and does no validation.
Fix Stripe API regression by passing name parameter for shipping details
=> Fix stripe charge params due to api change

models/download.go, models/order.go
Fixes #169
**- Summary**
Adding an index on `instance_id` and `created_at` will allow the dataset to be ordered and filtered a lot faster, especially when there are a lot of orders.
Also, since the custom names for indices are removed, indices will now be properly prefixed with the table namespace.
**Warning:**
Automigrations on large databases might take a little longer since the index will need to be populated.
There are no performance tests at all.
Apart from that, the existing tests cover most applications of the impacted fields.
Optimize sql queries by adding indices
=> Optimize indices for large tables

api/api.go, api/payments.go, api/payments_test.go, conf/configuration.go, models/transaction.go, payments/payments.go, payments/paypal/paypal.go, payments/stripe/stripe.go
Fixes #179 
**- Summary**
- Client: Create a payment method and pass that to POST /orders/:order_id/payments
- Server: Create a PaymentIntent with the payment method from the client - report back if the payment needs more actions (including the client secret for the payment intent)
- Client: Completes additional action and calls POST /payments/:payment_id/confirm
- Server: Responds with the result of checking if the transaction is completed, updates payment status on order
**Payload:**
```js
{
"provider": "stripe",
"stripe_payment_method_id": "<the id>"
}
```
**Response:** Transaction object
*(state if 3D secure is pending)*
```js
{
"id": "...", // transaction id
"order_id": "...",
"invoice_number": "...",
"processor_id": "...",
"user_id": "...",
"amount": "...",
"currency": "...", …
```
=> Support Strong Customer Authentication using Stripe with PaymentIntent

api/api.go, api/download.go, api/download_test.go, api/order.go, api/utils_test.go, models/line_item.go, models/order.go
Preparation step for #128
**- Summary**
This feature enables users to get access to downloads which have been added to products from their orders after their purchase. Changes in the product metadata are going to be picked up.
Use the endpoint `/orders/{order_id}/downloads/refresh` to fetch updates on demand.
There is an unfinished implementation of an automatic, periodic refresh task that is planned to be introduced soon. This is a first step.
There is a http test for the `/orders/{order_id}/downloads/refresh` endpoint
Refresh order downloads periodically and on demand
=> Refresh downloads on demand

api/payments.go
*Fixes #181*
**- Summary**
Bugfix related to giving db driver too many parameters
Hard to test a regression because it does not show up in sqlite...
Fix error on `/payments` endpoint.
=> Fix bug in transaction listing for admins

calculator/calculator.go, calculator/calculator_test.go
**- Summary**
Changes the way tax calculation is done when product listing prices include taxes (like in most VAT scenarios).
- Taxes are now calculated based on the original gross amount.
- Net total is calculated by subtracting taxes from gross amount.
- Updated tests to verify new behavior
- Added one new scenario that had wrong outcomes before
Calculate taxes based on original price if taxes are included
=> Calculate taxes based on original price if taxes are included

docker-compose.yml
**- Summary**
When first running this with docker-compose, the `api` fails immediately
because the `db` service is not yet running. This adds `depends_on` to
make sure the `db` service is running before the `api` service.
run `docker-compose up` and make sure `db` runs before `api` starts
Ensure `db` service runs before `api` service when running `docker-compose`
=> Make `api` service depend on `db` service in docker-compose

api/order.go
**- Summary**
When a 204 is sent, no content is allowed. But using `sendJSON` creates
a response body with empty content and a "Content-Type" header. This change
sets the status as 204, but returns no content as the spec requires.
fixes #189 
Call /claims with a proper request, and the error llog mentioned in #189 will not appear
Removed the body of the 204 response on a successful call to `/claims`
=> Updating response for succesful `/claims` request

api/payments.go, api/payments_test.go, conf/configuration.go, payments/stripe/stripe.go
**- Summary**
The Stripe payment provider was recently migrated to use the new PaymentIntent API.
This is required for EU countries as of Sept 14th 2019.
That change was behind a feature flag.
This change makes PaymentIntents the default and removes the flag.
n/a
Default to PaymentIntents for Stripe
=> Remove deprecated payments through stripe charges

api/payments.go
Also, only send order confirmation after confirmation, not when creating
the payment.
=> Prevent panic when sending payment confirm email

Dockerfile, go.mod, go.sum
**- Summary**
Follow up for #222 
It needs at least Go 1.15, but it shouldn't hurt to go to lastest.
Existing tests and staging.
Upgrade Go to 1.17
=> Upgrade to Go 1.17
